export const contacts = [
  {
    id: "dr-salma-nabil",
    name: "Dr. Salma Nabil",
    role: "Pediatric Neurologist",
    category: "Doctor",
    specialty: "medical",
    specialization: "Child development and neurological assessments",
    budgetLabel: "Premium",
    budgetValue: "EGP 900 / session",
    distanceLabel: "5 km away",
    review: 5.0,
    reviewLabel: "5.0 rating",
    reviewsCount: 148,
    status: "Available",
    phone: "+20 100 234 5678",
    email: "salma.nabil@inspirability.com",
    location: "Maadi, Cairo",
    availability: "Sun - Thu, 10:00 AM - 6:00 PM",
    contactHours: "Direct response within 2 hours",
    description:
      "Dr. Salma supports children and families with clear developmental plans, follow-up care, and coordinated specialist guidance for long-term progress.",
    image: "images/1.jpg",
  },
  {
    id: "omar-adel",
    name: "Omar Adel",
    role: "Fitness Coach",
    category: "Coach",
    specialty: "sports",
    specialization: "Adaptive movement and strength routines",
    budgetLabel: "Standard",
    budgetValue: "EGP 420 / session",
    distanceLabel: "12 km away",
    review: 4.8,
    reviewLabel: "4.8 rating",
    reviewsCount: 96,
    status: "Active",
    phone: "+20 101 345 6789",
    email: "omar.adel@inspirability.com",
    location: "Nasr City, Cairo",
    availability: "Sat - Wed, 4:00 PM - 10:00 PM",
    contactHours: "Phone and WhatsApp available",
    description:
      "Omar designs structured training plans that build confidence, consistency, and measurable athletic progress for different age groups and abilities.",
    image: "images/Trn 2.png",
  },
  {
    id: "mona-hesham",
    name: "Mona Hesham",
    role: "Math Teacher",
    category: "Teacher",
    specialty: "education",
    specialization: "Foundational math and learning support",
    budgetLabel: "Economy",
    budgetValue: "EGP 260 / lesson",
    distanceLabel: "6 km away",
    review: 4.6,
    reviewLabel: "4.6 rating",
    reviewsCount: 84,
    status: "Online",
    phone: "+20 102 456 7890",
    email: "mona.hesham@inspirability.com",
    location: "Heliopolis, Cairo",
    availability: "Sun - Thu, 1:00 PM - 7:00 PM",
    description:
      "Mona helps students strengthen core numeracy skills with patient instruction, visual methods, and lesson plans tailored to individual pace.",
    image: "images/Trn 1.png",
  },
  {
    id: "dr-karim-mostafa",
    name: "Dr. Karim Mostafa",
    role: "Speech Therapist",
    category: "Therapist",
    specialty: "therapy",
    specialization: "Speech fluency and communication development",
    budgetLabel: "Premium",
    budgetValue: "EGP 780 / session",
    distanceLabel: "14 km away",
    review: 4.9,
    reviewLabel: "4.9 rating",
    reviewsCount: 121,
    status: "Available",
    phone: "+20 103 567 8901",
    email: "karim.mostafa@inspirability.com",
    location: "Dokki, Giza",
    availability: "Sun - Wed, 11:00 AM - 8:00 PM",
    contactHours: "Clinic booking line available daily",
    description:
      "Dr. Karim focuses on practical communication outcomes, offering targeted therapy sessions, parent guidance, and progress-focused reporting.",
    image: "images/image (3).png",
  },
  {
    id: "nour-el-din",
    name: "Nour El Din",
    role: "English Teacher",
    category: "Teacher",
    specialty: "education",
    specialization: "Language confidence and reading development",
    budgetLabel: "Standard",
    budgetValue: "EGP 340 / lesson",
    distanceLabel: "30 km away",
    review: 4.5,
    reviewLabel: "4.5 rating",
    reviewsCount: 67,
    status: "Active",
    phone: "+20 104 678 9012",
    email: "nour.eldin@inspirability.com",
    location: "Online and New Cairo",
    availability: "Daily, 5:00 PM - 9:00 PM",
    description:
      "Nour works on spoken English, reading comprehension, and school-aligned language goals through engaging and structured sessions.",
    image: "images/image (2).png",
  },
  {
    id: "youssef-emad",
    name: "Youssef Emad",
    role: "Football Coach",
    category: "Coach",
    specialty: "sports",
    specialization: "Team coordination and youth football drills",
    budgetLabel: "Economy",
    budgetValue: "EGP 230 / session",
    distanceLabel: "8 km away",
    review: 4.8,
    reviewLabel: "4.8 rating",
    reviewsCount: 102,
    status: "Available",
    phone: "+20 105 789 0123",
    email: "youssef.emad@inspirability.com",
    location: "6th of October, Giza",
    availability: "Sat - Thu, 3:00 PM - 8:00 PM",
    description:
      "Youssef leads high-energy coaching sessions that balance technique, teamwork, and enjoyable routines for young players.",
    image: "images/Wadi Debla.jpg",
  },
  {
    id: "dr-farah-tarek",
    name: "Dr. Farah Tarek",
    role: "Behavioral Therapist",
    category: "Therapist",
    specialty: "therapy",
    specialization: "Behavior planning and parent coaching",
    budgetLabel: "Standard",
    budgetValue: "EGP 560 / session",
    distanceLabel: "28 km away",
    review: 5.0,
    reviewLabel: "5.0 rating",
    reviewsCount: 89,
    status: "Online",
    phone: "+20 106 890 1234",
    email: "farah.tarek@inspirability.com",
    location: "Online and Sheikh Zayed",
    availability: "Sun - Thu, 12:00 PM - 7:00 PM",
    contactHours: "Video consultation available",
    description:
      "Dr. Farah creates actionable behavior plans, supports home consistency, and helps families build sustainable strategies together.",
    image: "images/2025-12-22.png",
  },
  {
    id: "hadeer-samy",
    name: "Hadeer Samy",
    role: "Learning Support Teacher",
    category: "Teacher",
    specialty: "education",
    specialization: "Inclusive classroom support and study skills",
    budgetLabel: "Economy",
    budgetValue: "EGP 240 / lesson",
    distanceLabel: "11 km away",
    review: 4.7,
    reviewLabel: "4.7 rating",
    reviewsCount: 73,
    status: "Available",
    phone: "+20 107 901 2345",
    email: "hadeer.samy@inspirability.com",
    location: "Mokattam, Cairo",
    availability: "Sun - Wed, 2:00 PM - 8:00 PM",
    description:
      "Hadeer helps students organize schoolwork, build confidence, and manage learning goals through practical, supportive teaching sessions.",
    image: "images/image (1).png",
  },
  {
    id: "layla-hassan",
    name: "Layla Hassan",
    role: "Occupational Coach",
    category: "Coach",
    specialty: "therapy",
    specialization: "Daily living skills and independence routines",
    budgetLabel: "Premium",
    budgetValue: "EGP 690 / session",
    distanceLabel: "10 km away",
    review: 4.9,
    reviewLabel: "4.9 rating",
    reviewsCount: 112,
    status: "Active",
    phone: "+20 108 012 3456",
    email: "layla.hassan@inspirability.com",
    location: "Zamalek, Cairo",
    availability: "Mon - Fri, 9:00 AM - 5:00 PM",
    description:
      "Layla works on practical independence goals with calm, structured coaching that supports both children and caregivers.",
    image: "images/Trn 4.png",
  },
  {
    id: "rania-magdy",
    name: "Rania Magdy",
    role: "Special Education Teacher",
    category: "Teacher",
    specialty: "education",
    specialization: "Individualized education plans and literacy support",
    budgetLabel: "Standard",
    budgetValue: "EGP 380 / lesson",
    distanceLabel: "6 km away",
    review: 4.8,
    reviewLabel: "4.8 rating",
    reviewsCount: 91,
    status: "Available",
    phone: "+20 109 123 4567",
    email: "rania.magdy@inspirability.com",
    location: "Garden City, Cairo",
    availability: "Sun - Thu, 9:30 AM - 4:30 PM",
    description:
      "Rania combines curriculum planning, family communication, and differentiated instruction to support consistent academic growth.",
    image: "images/2.jpg",
  },
  {
    id: "amr-wael",
    name: "Amr Wael",
    role: "Swimming Coach",
    category: "Coach",
    specialty: "sports",
    specialization: "Technique correction and water confidence",
    budgetLabel: "Standard",
    budgetValue: "EGP 400 / session",
    distanceLabel: "35 km away",
    review: 4.6,
    reviewLabel: "4.6 rating",
    reviewsCount: 64,
    status: "Active",
    phone: "+20 110 234 5678",
    email: "amr.wael@inspirability.com",
    location: "Alexandria Road clubs",
    availability: "Fri - Tue, 8:00 AM - 2:00 PM",
    description:
      "Amr delivers disciplined swimming sessions focused on technique, safety, and gradual confidence building in the water.",
    image: "images/Trn 3.png",
  },
  {
    id: "dr-dina-ashraf",
    name: "Dr. Dina Ashraf",
    role: "Occupational Therapist",
    category: "Doctor",
    specialty: "medical",
    specialization: "Fine motor development and sensory support",
    budgetLabel: "Premium",
    budgetValue: "EGP 860 / session",
    distanceLabel: "7 km away",
    review: 5.0,
    reviewLabel: "5.0 rating",
    reviewsCount: 137,
    status: "Online",
    phone: "+20 111 345 6789",
    email: "dina.ashraf@inspirability.com",
    location: "New Cairo",
    availability: "Sun - Thu, 10:00 AM - 6:30 PM",
    contactHours: "Priority booking for follow-up families",
    description:
      "Dr. Dina provides thoughtful occupational therapy plans with measurable goals, caregiver guidance, and child-friendly session design.",
    image: "images/uKcdpmEDDhJjXhty2dodjnQah4AdNSMvX4OpbhDZ.jpeg",
  },
];
